/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_walker_safecopy_SafeCopy */

#ifndef _Included_com_walker_safecopy_SafeCopy
#define _Included_com_walker_safecopy_SafeCopy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_walker_safecopy_SafeCopy
 * Method:    putString2memory
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_walker_safecopy_SafeCopy_putString2memory
        (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_walker_safecopy_SafeCopy
 * Method:    getString4memory
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 *
 */
JNIEXPORT jstring JNICALL Java_com_walker_safecopy_SafeCopy_getString4memory
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
